### ISSUE TITLE
FileClient - check for operation success with upload/download

### ISSUE THREAD

**Issue by mrsell** [ID132457890/CSS434_Final_Project#1]
Might want to consider using the return value from upload/download server RMI calls - the return value represents operation success, and there might not be an exception thrown if there was a problem.

I was referring to the state-transition diagram in section 4. (probably mentioned elsewhere, too)

**Comment by ID132457890** [comment]
That's a good call! I know that upload returns a boolean, but does download return null if it failed?

**Comment by ID132457890** [comment]
Well, I'm dumb: just had to look at your code to figure it out.

**Comment by ID132457890** [comment]
Done!
