### ISSUE TITLE
FileClient - some exceptions should not be swallowed

### ISSUE THREAD

**Issue by mrsell** [ID132457890/CSS434_Final_Project#5]
For example, in the constructor, the "catch" blocks should terminate the application because those are unrecoverable errors. Instead, the program continues in an invalid state without the user knowing that it can't run correctly.

Another example is in "download", where an exception in calling download on the server results in a "false" being returned, but the call in "startClient" will continue to launch emacs even though the file was not downloaded.

**Comment by ID132457890** [comment]
That's a good point and also the sort of stuff that I never pay attention to while coding.

**Comment by ID132457890** [comment]
Just submitted a new file. Exceptions in the constructor terminate the program and now, if download returns false, emacs won't show up.
